name: Deploy NLP API to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: my-project-avis-nlp
  REGION: europe-west1
  SERVICE_NAME: reddit-nlp-api
  REPOSITORY: reddit-api
  IMAGE: europe-west1-docker.pkg.dev/my-project-avis-nlp/reddit-api/reddit-nlp-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4


      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}


      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2


      - name: Configure Docker authentication
        run: |
          gcloud auth configure-docker europe-west1-docker.pkg.dev


      - name: Build Docker image
        run: |
          docker build -t $IMAGE .


      - name: Push Docker image
        run: |
          docker push $IMAGE


      - name: Deploy Cloud Run
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated